#!/bin/bash
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_201-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_201-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_201-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_201-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_201-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_201-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_202-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_202-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_202-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_202-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_202-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_202-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_203-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_203-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_203-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_203-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_203-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_203-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_204-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_204-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_204-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_204-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_204-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_204-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_205-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_205-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_205-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_205-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_205-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_205-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_206-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_206-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_206-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_206-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_206-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_206-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_207-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_207-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_207-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_207-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_207-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_207-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_208-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_208-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_208-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_208-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_208-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_208-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_209-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_209-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_209-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_209-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_209-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_209-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_210-225.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_210-226.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_210-227.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_210-228.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_210-229.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_210-230.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/ISIMIP_HISTORICAL_METADATA.pbz2 ./
