#!/bin/bash
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_190-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_190-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_190-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_190-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_190-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_190-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_191-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_191-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_191-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_191-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_191-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_191-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_192-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_192-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_192-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_192-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_192-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_192-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_193-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_193-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_193-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_193-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_193-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_193-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_194-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_194-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_194-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_194-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_194-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_194-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_195-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_195-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_195-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_195-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_195-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_195-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_196-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_196-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_196-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_196-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_196-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_196-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_197-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_197-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_197-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_197-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_197-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_197-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_198-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_198-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_198-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_198-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_198-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_198-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_199-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_199-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_199-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_199-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_199-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_199-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-255.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-256.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-257.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-258.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-259.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/input_data_200-260.pbz2 ./
scp sombrero:/home/amazonfaceme/shared_data/HISTORICAL-RUN/ISIMIP_HISTORICAL_METADATA.pbz2 ./
