! Copyright 2017- LabTerra

!     This program is free software: you can redistribute it and/or modify
!     it under the terms of the GNU General Public License as published by
!     the Free Software Foundation, either version 3 of the License, or
!     (at your option) any later version.

!     This program is distributed in the hope that it will be useful,
!     but WITHOUT ANY WARRANTY; without even the implied warranty of
!     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!     GNU General Public License for more details.

!     You should have received a copy of the GNU General Public License
!     along with this program.  If not, see <http://www.gnu.org/licenses/>.

! This program is based on the work of those that gave us the INPE-CPTEC-PVM2 model

! This file is generated by the script ask_npls.py
! If you want to change any parameter, please, edit the script and compile the code again

module photo_par
   use types, only : r_8
   implicit none
   private

   real(r_8),public, parameter ::       &
        a   = 0.8300D0       ,&          !Photosynthesis co-limitation coefficient
        a2  = 0.930D0        ,&          !Photosynthesis co-limitation coefficient
        p3  = 21200.0D0      ,&          !Atmospheric oxygen concentration (Pa)
        p4  = 0.080D0        ,&          !Quantum efficiency (mol electrons/Ein)
        p5  = 0.150D0        ,&          !Light scattering rate
        p6  = 2.0D0          ,&          !Parameter for jl
        p7  = 0.50D0         ,&          !Ratio of light limited photosynthesis to Rubisco carboxylation
        p8  = 5200.0D0       ,&          !Photo-respiration compensation point
        p9  = 0.570D0        ,&          !Photosynthesis co-limitation coefficient
        p10 = 0.100D0        ,&          !Q10 function
        p11 = 25.0D0         ,&          !Q10 function reference temperature (oC)
        p12 = 30.0D0         ,&          !Michaelis-Menten constant for CO2 (Pa)
        p13 = 2.100D0        ,&          !Michaelis-Menten constant for CO2
        p14 = 30000.0D0      ,&          !Michaelis-Menten constant for O2 (Pa)
        p15 = 1.20D0         ,&          !Michaelis-Menten constant for O2
        p19 = 0.90D0         ,&          !Maximum ratio of internal to external CO2
        p20 = 0.10D0         ,&          !Critical humidity deficit (kg/kg)
        p25 = 80.0D-6        ,&          !Maximum gross photosynthesis rate (molCO2/m2/s)
        p26 = 0.50D0         ,&          !light extinction coefficient for IPAR/sun (0.5/sen90)
        p27 = 1.50D0         ,&          !light extinction coefficient for IPAR/shade (0.5/sen20)
        alphap = 0.0913D0    ,&          ! 0.0913 parameter for v4m (c4 photosynthesis) Chen et al. 1994
        vpm25 =  85.0D0      ,&          ! µmol m-2 s-1 PEPcarboxylase CO2 saturated rate of carboxilation at 25°C
        h_vpm = 185075.0D0   ,&          ! Arrhenius eq. constant
        s_vpm = 591.0D0      ,&          ! Arrhenius eq. constant
        r_vpm = 8.314D0      ,&          ! Arrhenius eq. constant
        e_vpm = 60592.0D0    ,&          ! Arrhenius eq. constant
        kp25 = 82.0D0        ,&          !µmol mol-1 (ppm)
        gap_fraction = 0.25D0             !Fraction of gap in the canopy

end module photo_par