! Copyright 2017- LabTerra

!     This program is free software: you can redistribute it and/or modify
!     it under the terms of the GNU General Public License as published by
!     the Free Software Foundation, either version 3 of the License, or
!     (at your option) any later version.

!     This program is distributed in the hope that it will be useful,
!     but WITHOUT ANY WARRANTY; without even the implied warranty of
!     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
!     GNU General Public License for more details.

!     You should have received a copy of the GNU General Public License
!     along with this program.  If not, see <http://www.gnu.org/licenses/>.

! This program is based on the work of those that gave us the INPE-CPTEC-PVM2 model

! This file is generated by the script ask_npls.py
! If you want to change any parameter, please, edit the script and compile the code again


module types
   implicit none
   private
   ! tested in gfortran, ifx, and AOCC-flang
   integer,parameter,public :: l_1 = 2  ! standard Logical type
   integer,parameter,public :: i_2 = 2  ! 16 bits integer
   integer,parameter,public :: i_4 = 4  ! 32 bits integer
   integer,parameter,public :: r_4 = 4  ! 32 bits float
   integer,parameter,public :: r_8 = 8  ! 64 bits float

end module types


! module types
!    use iso_fortran_env, only : int16
!    implicit none
!    private

!    integer,parameter,public :: l_1 = kind(.true.)  ! standard Logical type
!    integer,parameter,public :: i_2 = int16         ! 16 bits integer
!    integer,parameter,public :: i_4 = kind(0)       ! 32 bits integer
!    integer,parameter,public :: r_8 = kind(0.0)     ! 32 bits float
!    integer,parameter,public :: r_8 = kind(0.0D0)   ! 64 bits float

! end module types